# Generated by Django 5.2 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_formsubmission_telegram_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('cs', 'Čeština'), ('en', 'English')], db_index=True, default='', max_length=5, verbose_name='Бажана мова спілкування'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='address',
            field=models.CharField(default='Київ, бульвар Тараса Шевченка 46а, Україна', max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='legal_address',
            field=models.CharField(default='Полтавська обл., м. Миргород, вул. Кваші, буд 2, Україна', help_text='Місце реєстрації ФОП; фактична адреса — поле «Адреса» вище.', max_length=255, verbose_name='Юридична адреса (Impressum)'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='phone_display',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон (відображення)'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='phone_e164',
            field=models.CharField(blank=True, default='', help_text='Без +, наприклад 380639520565. Залиште порожнім, якщо телефон не показуємо.', max_length=20, verbose_name='Телефон (цифри для посилань)'),
        ),
    ]
