# Generated by Django 5.2 on 2026-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitecontactsettings_phone_blank_address_ukraine'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='czechia_address',
            field=models.CharField(blank=True, default='Praha, Česko', help_text='Друга публічна адреса (CZ). Порожнє = не показувати.', max_length=255, verbose_name='Адреса в Чехії'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='czechia_address_cs',
            field=models.CharField(blank=True, default='Praha, Česko', max_length=255, verbose_name='Адреса в Чехії (CS)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='czechia_address_en',
            field=models.CharField(blank=True, default='Prague, Czechia', max_length=255, verbose_name='Адреса в Чехії (EN)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Ім'я"),
        ),
    ]
