"""Дефолтні CMS-блоки demo-корпоративного сайту PrometeyLabs (registry-driven, «Мій сайт»)."""
from django.utils.translation import gettext_lazy as _

TEXT = 'text'
IMAGE = 'image'
BOOL = 'bool'

PAGE_LABELS = {
    'header': _('Хедер'),
    'home': _('Головна'),
    'production': _('Як працюємо'),
    'about': _('Про нас'),
    'contacts': _('Контакти'),
    'catalog': _('Приклади'),
    'cta': _('Заклик до дії'),
    'footer': _('Футер'),
    'seo': _('SEO'),
}

BLOCK_REGISTRY = [
    {'page': 'header', 'key': 'company_name', 'type': TEXT, 'label': _('Назва компанії (лого)'),
     'default': 'PrometeyLabs', 'default_en': 'PrometeyLabs', 'default_cs': 'PrometeyLabs'},

    {'page': 'home', 'key': 'hero_title', 'type': TEXT, 'label': _('Заголовок hero'), 'multiline': True,
     'default': 'Pár stránek — a lidé vám napíšou',
     'default_en': 'A few clear pages — and people get in touch',
     'default_cs': 'Pár stránek — a lidé vám napíšou'},
    {'page': 'home', 'key': 'hero_subtitle', 'type': TEXT, 'label': _('Підзаголовок hero'), 'multiline': True,
     'default': 'Domů, služby, o nás, kontakty. Srozumitelná slova, pohodlné v telefonu. Texty pak měníte sami.',
     'default_en': 'Home, services, about, contacts. Clear copy, comfortable on mobile. You edit the texts yourself later.',
     'default_cs': 'Domů, služby, o nás, kontakty. Srozumitelná slova, pohodlné v telefonu. Texty pak měníte sami.'},
    {'page': 'home', 'key': 'hero_cta_label', 'type': TEXT, 'label': _('Текст кнопки hero'),
     'default': 'Chci takový web', 'default_en': 'Get a site like this',
     'default_cs': 'Chci takový web'},
    {'page': 'home', 'key': 'stat_years', 'type': TEXT, 'label': _('Статистика: днів до старту'),
     'default': '14', 'default_en': '14', 'default_cs': '14'},
    {'page': 'home', 'key': 'stat_windows', 'type': TEXT, 'label': _('Статистика: сторінок'),
     'default': '6', 'default_en': '6', 'default_cs': '6'},
    {'page': 'home', 'key': 'stat_warranty', 'type': TEXT, 'label': _('Статистика: зручно з телефону'),
     'default': '100', 'default_en': '100', 'default_cs': '100'},
    {'page': 'home', 'key': 'stat_dealers', 'type': TEXT, 'label': _('Статистика: мов'),
     'default': '4', 'default_en': '4', 'default_cs': '4'},
    {'page': 'home', 'key': 'stat_windows_label', 'type': TEXT, 'label': _('Підпис KPI: сторінки'),
     'default': 'stránek v sadě', 'default_en': 'pages in the set',
     'default_cs': 'stránek v sadě'},
    {'page': 'home', 'key': 'stat_years_label', 'type': TEXT, 'label': _('Підпис KPI: дні'),
     'default': 'dní do startu', 'default_en': 'days to launch',
     'default_cs': 'dní do startu'},
    {'page': 'home', 'key': 'stat_warranty_label', 'type': TEXT, 'label': _('Підпис KPI: телефон'),
     'default': 'pohodlné v telefonu', 'default_en': 'mobile-friendly',
     'default_cs': 'pohodlné v telefonu'},
    {'page': 'home', 'key': 'stat_dealers_label', 'type': TEXT, 'label': _('Підпис KPI: мови'),
     'default': 'jazyky hned', 'default_en': 'languages from day one',
     'default_cs': 'jazyky hned'},
    {'page': 'home', 'key': 'reviews_visible', 'type': BOOL, 'label': _('Показувати відгуки на головній'),
     'default': '1'},
    {'page': 'home', 'key': 'reviews_title', 'type': TEXT, 'label': _('Заголовок відгуків'),
     'default': 'Lidé, kteří už objednali', 'default_en': 'Clients who already ordered',
     'default_cs': 'Lidé, kteří už objednali'},
    {'page': 'home', 'key': 'partners_visible', 'type': BOOL, 'label': _('Показувати партнерів на головній'),
     'default': '1'},
    {'page': 'home', 'key': 'catalog_teaser_title', 'type': TEXT, 'label': _('Заголовок блоку каталогу на головній'),
     'default': 'Příklady webů, které si můžete objednat',
     'default_en': 'Example sites you can commission',
     'default_cs': 'Příklady webů, které si můžete objednat'},

    {'page': 'production', 'key': 'title', 'type': TEXT, 'label': _('Заголовок сторінки «Як працюємо»'),
     'default': 'Jak děláme firemní web',
     'default_en': 'How we build a corporate site',
     'default_cs': 'Jak děláme firemní web'},
    {'page': 'production', 'key': 'intro', 'type': TEXT, 'label': _('Вступний текст'), 'multiline': True,
     'default': 'Tento demo web je živý příklad. Stejně sestavíme domů, služby, o nás a kontakty pro vaši firmu.',
     'default_en': 'This demo is a live example. We assemble home, services, about and contacts for your company the same way.',
     'default_cs': 'Tento demo web je živý příklad. Stejně sestavíme domů, služby, o nás a kontakty pro vaši firmu.'},
    {'page': 'production', 'key': 'step_1', 'type': TEXT, 'label': _('Етап 1'),
     'default': 'Řeknete, kdo je vaše firma',
     'default_en': 'You tell us about your company',
     'default_cs': 'Řeknete, kdo je vaše firma'},
    {'page': 'production', 'key': 'step_2', 'type': TEXT, 'label': _('Етап 2'),
     'default': 'Ukážeme strukturu stránek',
     'default_en': 'We present the page structure',
     'default_cs': 'Ukážeme strukturu stránek'},
    {'page': 'production', 'key': 'step_3', 'type': TEXT, 'label': _('Етап 3'),
     'default': 'Sestavíme web a napojíme poptávky',
     'default_en': 'We build the site and connect enquiries',
     'default_cs': 'Sestavíme web a napojíme poptávky'},
    {'page': 'production', 'key': 'step_4', 'type': TEXT, 'label': _('Етап 4'),
     'default': 'Vstoupíte do adminu a upravujete sami',
     'default_en': 'You log into the admin and edit it yourself',
     'default_cs': 'Vstoupíte do adminu a upravujete sami'},
    {'page': 'production', 'key': 'certificates_visible', 'type': BOOL, 'label': _('Показувати додаткові екрани'),
     'default': '1'},

    {'page': 'about', 'key': 'title', 'type': TEXT, 'label': _('Заголовок «Про нас»'),
     'default': 'Weby pro firmy', 'default_en': 'Websites for companies',
     'default_cs': 'Weby pro firmy'},
    {'page': 'about', 'key': 'text', 'type': TEXT, 'label': _('Текст «Про нас»'), 'multiline': True,
     'default': 'PrometeyLabs dělá firemní weby: ne konstruktor a ne cizí šablona. Toto demo je to, co dostanete: stránky, poptávky, admin, pohodlné v telefonu.\n\nDomů, služby, o nás a kontakty sestavíme pro vaši firmu. Texty pak měníte sami. Poptávka ze webu přijde vám — stejně jako na tomto demu.\n\nWeb má vypadat vážně ve vyhledávání i v telefonu: bez štípnutí a bez «zavolejte, domluvíme se».',
     'default_en': 'PrometeyLabs builds corporate sites: not a page builder and not someone else’s template. This demo is what you get: pages, enquiries, an admin — mobile-friendly.\n\nWe assemble home, services, about and contacts for your company. You edit the texts yourself later. An enquiry from the site comes to you — the same as on this demo.\n\nThe site should look credible in search and on mobile: no pinch-to-zoom and no “call us, we’ll figure it out”.',
     'default_cs': 'PrometeyLabs dělá firemní weby: ne konstruktor a ne cizí šablona. Toto demo je to, co dostanete: stránky, poptávky, admin, pohodlné v telefonu.\n\nDomů, služby, o nás a kontakty sestavíme pro vaši firmu. Texty pak měníte sami. Poptávka ze webu přijde vám — stejně jako na tomto demu.\n\nWeb má vypadat vážně ve vyhledávání i v telefonu: bez štípnutí a bez «zavolejte, domluvíme se».'},
    {'page': 'about', 'key': 'mission', 'type': TEXT, 'label': _('Місія'), 'multiline': True,
     'default': 'Firma má vypadat vážně ve vyhledávání i v telefonu. Člověk přijde — pochopí — nechá poptávku.',
     'default_en': 'A company should look credible in search and on mobile. A visitor arrives, understands, and gets in touch.',
     'default_cs': 'Firma má vypadat vážně ve vyhledávání i v telefonu. Člověk přijde — pochopí — nechá poptávku.'},
    {'page': 'about', 'key': 'approach', 'type': TEXT, 'label': _('Як збираємо'), 'multiline': True,
     'default': 'Krátký hovor — struktura stránek — stavba — vy v adminu. Uvidíte domů, služby, o nás a kontakty před spuštěním. Formulář, telefon a sítě napojíme hned: poptávka se neztratí v Directu.',
     'default_en': 'A short call — page structure — build — you in the admin. You see home, services, about and contacts before launch. Form, phone and socials are connected at once: the enquiry does not get lost in DMs.',
     'default_cs': 'Krátký hovor — struktura stránek — stavba — vy v adminu. Uvidíte domů, služby, o nás a kontakty před spuštěním. Formulář, telefon a sítě napojíme hned: poptávka se neztratí v Directu.'},
    {'page': 'about', 'key': 'audience', 'type': TEXT, 'label': _('Для кого'), 'multiline': True,
     'default': 'Firmám, které potřebují stránku pro partnery a klienty, ne landing na tři obrazovky. Výroba, klinika, škola, agentura — několik srozumitelných stránek a poptávky v jednom adminu.',
     'default_en': 'For companies that need pages for partners and clients — not a three-screen landing. Manufacturing, a clinic, a school, an agency: a few clear pages and enquiries in one admin.',
     'default_cs': 'Firmám, které potřebují stránku pro partnery a klienty, ne landing na tři obrazovky. Výroba, klinika, škola, agentura — několik srozumitelných stránek a poptávky v jednom adminu.'},
    {'page': 'about', 'key': 'photo', 'type': IMAGE, 'label': _('Фото «Про нас»')},

    {'page': 'contacts', 'key': 'address', 'type': TEXT, 'label': _('Адреса'),
     'default': 'Kyjev, Tarase Ševčenka 46a',
     'default_en': 'Prague, Czechia',
     'default_cs': 'Kyjev, Tarase Ševčenka 46a'},
    {'page': 'contacts', 'key': 'schedule', 'type': TEXT, 'label': _('Графік роботи'),
     'default': 'Po–Pá: 10:00–19:00 · konzultace po hovoru',
     'default_en': 'Mon–Fri: 10:00–19:00 · consultation by phone',
     'default_cs': 'Po–Pá: 10:00–19:00 · konzultace po hovoru'},
    {'page': 'contacts', 'key': 'phone', 'type': TEXT, 'label': _('Телефон'),
     'default': '+38 (063) 952-05-65', 'default_en': '+420 777 000 000',
     'default_cs': '+38 (063) 952-05-65'},
    {'page': 'contacts', 'key': 'email', 'type': TEXT, 'label': _('Email'),
     'default': 'info@prometeylabs.com', 'default_en': 'info@prometeylabs.com',
     'default_cs': 'info@prometeylabs.com'},

    {'page': 'catalog', 'key': 'title', 'type': TEXT, 'label': _('Заголовок каталогу'),
     'default': 'Příklady firemních webů',
     'default_en': 'Corporate website examples',
     'default_cs': 'Příklady firemních webů'},
    {'page': 'catalog', 'key': 'buy_cta_label', 'type': TEXT, 'label': _('Текст кнопки «Купити»'),
     'default': 'Chci takový web', 'default_en': 'Get a site like this',
     'default_cs': 'Chci takový web'},

    {'page': 'cta', 'key': 'title', 'type': TEXT, 'label': _('Заголовок CTA-секції'), 'multiline': True,
     'default': 'Nechte poptávku',
     'default_en': 'Get in touch',
     'default_cs': 'Nechte poptávku'},
    {'page': 'cta', 'key': 'subtitle', 'type': TEXT, 'label': _('Підпис CTA-секції'), 'multiline': True,
     'default': 'Nechte telefon — ukážeme, jak budou vaše stránky vypadat.',
     'default_en': 'Leave your phone number — we’ll show how your pages will look.',
     'default_cs': 'Nechte telefon — ukážeme, jak budou vaše stránky vypadat.'},
    {'page': 'cta', 'key': 'point_1', 'type': TEXT, 'label': _('Пункт CTA 01'),
     'default': 'Několik stránek v balíčku',
     'default_en': 'Several pages in the package',
     'default_cs': 'Několik stránek v balíčku'},
    {'page': 'cta', 'key': 'point_2', 'type': TEXT, 'label': _('Пункт CTA 02'),
     'default': 'Poptávky přijdou vám',
     'default_en': 'Enquiries come to you',
     'default_cs': 'Poptávky přijdou vám'},
    {'page': 'cta', 'key': 'point_3', 'type': TEXT, 'label': _('Пункт CTA 03'),
     'default': 'Texty upravujete sami',
     'default_en': 'You edit the texts yourself',
     'default_cs': 'Texty upravujete sami'},
    {'page': 'cta', 'key': 'note', 'type': TEXT, 'label': _('Примітка під кнопкою заявки'),
     'default': 'Odpovíme během pracovního dne',
     'default_en': 'We reply within one business day',
     'default_cs': 'Odpovíme během pracovního dne'},
    {'page': 'cta', 'key': 'submit_label', 'type': TEXT, 'label': _('Текст кнопки відправки заявки'),
     'default': 'Nechat poptávku', 'default_en': 'Get in touch', 'default_cs': 'Nechat poptávku'},

    {'page': 'footer', 'key': 'partners_visible', 'type': BOOL, 'label': _('Показувати партнерів у футері'),
     'default': '1'},

    {'page': 'seo', 'key': 'title', 'type': TEXT, 'label': _('SEO title'),
     'default': 'PrometeyLabs — firemní web, ze kterého píšou',
     'default_en': 'PrometeyLabs — a corporate site that brings enquiries',
     'default_cs': 'PrometeyLabs — firemní web, ze kterého píšou'},
    {'page': 'seo', 'key': 'description', 'type': TEXT, 'label': _('SEO description'), 'multiline': True,
     'default': 'Objednejte firemní web: několik stránek, poptávky, jednoduchý admin, rychle v telefonu. Toto demo je živý příklad.',
     'default_en': 'Commission a corporate site: several pages, enquiries, a simple admin, mobile-friendly and fast. This demo is a live example.',
     'default_cs': 'Objednejte firemní web: několik stránek, poptávky, jednoduchý admin, rychle v telefonu. Toto demo je živý příklad.'},
]
