"""Seed-колекції demo-корпоративного сайту PrometeyLabs Czechia (CS/EN — PrometeyLabs Czechia)."""

PRODUCTION_STEPS = [
    {
        'title': 'Řeknete, kdo je vaše firma',
        'title_en': 'You tell us about your company',
        'title_cs': 'Řeknete, kdo je vaše firma',
        'description': 'Krátký hovor: komu prodáváte, které stránky potřebujete, kam mají padat poptávky.',
        'description_en': 'A short call: who you sell to, which pages you need, where enquiries should go.',
        'description_cs': 'Krátký hovor: komu prodáváte, které stránky potřebujete, kam mají padat poptávky.',
    },
    {
        'title': 'Ukážeme strukturu stránek',
        'title_en': 'We present the page structure',
        'title_cs': 'Ukážeme strukturu stránek',
        'description': 'Uvidíte domů, služby, o nás a kontakty před stavbou — bez překvapení po spuštění.',
        'description_en': 'You see home, services, about and contacts before we build — no surprises after launch.',
        'description_cs': 'Uvidíte domů, služby, o nás a kontakty před stavbou — bez překvapení po spuštění.',
    },
    {
        'title': 'Sestavíme web a napojíme poptávky',
        'title_en': 'We build the site and connect enquiries',
        'title_cs': 'Sestavíme web a napojíme poptávky',
        'description': 'Formulář, telefon, sítě. Poptávka ze webu přijde vám — toto demo funguje stejně.',
        'description_en': 'Form, phone, socials. An enquiry from the site comes to you — this demo works the same way.',
        'description_cs': 'Formulář, telefon, sítě. Poptávka ze webu přijde vám — toto demo funguje stejně.',
    },
    {
        'title': 'Vstoupíte do adminu a upravujete sami',
        'title_en': 'You log into the admin and edit it yourself',
        'title_cs': 'Vstoupíte do adminu a upravujete sami',
        'description': 'Texty, fotky a barvy bez programátora na každé «změňte slovo».',
        'description_en': 'Texts, photos and colours — no developer for every “change this word”.',
        'description_cs': 'Texty, fotky a barvy bez programátora na každé «změňte slovo».',
    },
]

GALLERY = [
    {'image': 'gallery/tilt-cards.webp', 'kind': 'production',
     'caption': 'Karty, které se naklánějí', 'caption_en': 'Cards that tilt',
     'caption_cs': 'Karty, které se naklánějí'},
    {'image': 'gallery/menu.webp', 'kind': 'production',
     'caption': 'Menu pohodlné v telefonu', 'caption_en': 'A menu that works on mobile',
     'caption_cs': 'Menu pohodlné v telefonu'},
    {'image': 'gallery/stats.webp', 'kind': 'production',
     'caption': 'Čísla, která se načítají', 'caption_en': 'Numbers that count up',
     'caption_cs': 'Čísla, která se načítají'},
    {'image': 'gallery/form.webp', 'kind': 'production',
     'caption': 'Formulář, po kterém vám napíšou', 'caption_en': 'A form that brings enquiries',
     'caption_cs': 'Formulář, po kterém vám napíšou'},
    {'image': 'gallery/admin.webp', 'kind': 'certificate',
     'caption': 'Admin, kde upravujete sami', 'caption_en': 'An admin you edit yourself',
     'caption_cs': 'Admin, kde upravujete sami'},
    {'image': 'gallery/phone.webp', 'kind': 'certificate',
     'caption': 'Rychle v telefonu', 'caption_en': 'Fast on mobile',
     'caption_cs': 'Rychle v telefonu'},
]

TESTIMONIALS = [
    {
        'author_name': 'Elena K.', 'role': 'Klinika, Praha', 'rating': 5,
        'text': 'Lidé se objednávají z webu. Už desetkrát nevysvětluju služby v Directu.',
        'text_en': 'People book from the site. I no longer explain services in DMs ten times over.',
        'text_cs': 'Lidé se objednávají z webu. Už desetkrát nevysvětluju služby v Directu.',
    },
    {
        'author_name': 'Igor M.', 'role': 'Výroba, Brno', 'rating': 5,
        'text': 'Partneři se podívají na O nás a hned napíšou. V telefonu je vše jasné.',
        'text_en': 'Partners read About and write right away. Everything is clear on mobile.',
        'text_cs': 'Partneři se podívají na O nás a hned napíšou. V telefonu je vše jasné.',
    },
    {
        'author_name': 'Marina T.', 'role': 'Agentura', 'rating': 5,
        'text': 'Šest stránek místo tří sešitů na Instagramu. Poptávky v jednom adminu.',
        'text_en': 'Six pages instead of three Instagram notebooks. Enquiries in one admin.',
        'text_cs': 'Šest stránek místo tří sešitů na Instagramu. Poptávky v jednom adminu.',
    },
    {
        'author_name': 'David V.', 'role': 'Stavební firma', 'rating': 5,
        'text': 'Texty měním sama za minutu. Reklama míň utíká — stránka lidi neodrazuje.',
        'text_en': 'I change the texts myself in a minute. Ads convert better — the page doesn’t push people away.',
        'text_cs': 'Texty měním sama za minutu. Reklama míň utíká — stránka lidi neodrazuje.',
    },
    {
        'author_name': 'Sofie L.', 'role': 'Škola, Ostrava', 'rating': 5,
        'text': 'Rodiče pochopí programy z první obrazovky. Zápis jde vám, neztratí se v Directu.',
        'text_en': 'Parents understand the programmes from the first screen. Bookings come to you — not lost in DMs.',
        'text_cs': 'Rodiče pochopí programy z první obrazovky. Zápis jde vám, neztratí se v Directu.',
    },
]

PARTNERS = ['Google', 'TikTok', 'Viber', 'YouTube', 'WhatsApp', 'Maps']

CATEGORIES = [
    {
        'name': 'Firmy', 'name_en': 'Companies', 'name_cs': 'Firmy',
    },
    {
        'name': 'Služby', 'name_en': 'Services', 'name_cs': 'Služby',
    },
    {
        'name': 'Výroba', 'name_en': 'Production', 'name_cs': 'Výroba',
    },
    {
        'name': 'Objednávky a vzdělávání', 'name_en': 'Booking and education',
        'name_cs': 'Objednávky a vzdělávání',
    },
]

PRODUCTS = [
    {
        'category': 0, 'name': 'Web firmy', 'name_en': 'Company site',
        'name_cs': 'Web firmy',
        'price_from': None,
        'excerpt': 'Domů, o nás, kontakty. Firma vypadá vážně — poptávky jdou vám.',
        'excerpt_en': 'Home, about, contacts. The company looks credible — enquiries come to you.',
        'excerpt_cs': 'Domů, o nás, kontakty. Firma vypadá vážně — poptávky jdou vám.',
        'specs': 'Stránky: 5–6\nAdmin: ano\nPoptávky: formulář + telefon',
        'specs_en': 'Pages: 5–6\nAdmin: yes\nRequests: form + phone',
        'specs_cs': 'Stránky: 5–6\nAdmin: ano\nPoptávky: formulář + telefon',
        'image': 'examples/company.webp',
    },
    {
        'category': 0, 'name': 'Vícejazyčný web', 'name_en': 'Multilingual site',
        'name_cs': 'Vícejazyčný web',
        'price_from': None,
        'excerpt': 'Čeština a angličtina na veřejném webu. Toto demo je tak sestavené.',
        'excerpt_en': 'Czech and English on the public site. This demo is built that way.',
        'excerpt_cs': 'Čeština a angličtina na veřejném webu. Toto demo je tak sestavené.',
        'specs': 'Jazyky: CS / EN\nStránky: 6+\nAdmin: ano',
        'specs_en': 'Languages: CS / EN\nPages: 6+\nAdmin: yes',
        'specs_cs': 'Jazyky: CS / EN\nStránky: 6+\nAdmin: ano',
        'image': 'examples/multilingual.webp',
    },
    {
        'category': 1, 'name': 'Web s katalogem služeb', 'name_en': 'Site with a services catalog',
        'name_cs': 'Web s katalogem služeb',
        'price_from': None,
        'excerpt': 'Karty služeb, stránka každé, tlačítko «chci tak». Jako katalog na tomto demu.',
        'excerpt_en': 'Service cards, a page for each, an “I want this” button. Like the catalogue on this demo.',
        'excerpt_cs': 'Karty služeb, stránka každé, tlačítko «chci tak». Jako katalog na tomto demu.',
        'specs': 'Katalog: ano\nPoptávka ze služby: ano\nAdmin: ano',
        'specs_en': 'Catalog: yes\nRequest from a service: yes\nAdmin: yes',
        'specs_cs': 'Katalog: ano\nPoptávka ze služby: ano\nAdmin: ano',
        'image': 'examples/catalog.webp',
    },
    {
        'category': 1, 'name': 'Web agentury', 'name_en': 'Agency site',
        'name_cs': 'Web agentury',
        'price_from': None,
        'excerpt': 'Případy, recenze, jak pracujete. Člověk pochopí, s kým má co do činění.',
        'excerpt_en': 'Case studies, reviews, how you work. Visitors understand who they are dealing with.',
        'excerpt_cs': 'Případy, recenze, jak pracujete. Člověk pochopí, s kým má co do činění.',
        'specs': 'Stránky: o nás + proces\nRecenze: ano\nPoptávky: ano',
        'specs_en': 'Pages: about + process\nReviews: yes\nRequests: yes',
        'specs_cs': 'Stránky: o nás + proces\nRecenze: ano\nPoptávky: ano',
        'image': 'examples/agency.webp',
    },
    {
        'category': 2, 'name': 'Web výroby', 'name_en': 'Production site',
        'name_cs': 'Web výroby',
        'price_from': None,
        'excerpt': 'Kroky, galerie provozu, certifikáty. Partner vidí, jak děláte — nejen slogan.',
        'excerpt_en': 'Steps, shop-floor gallery, certificates. Partners see how you work — not just a slogan.',
        'excerpt_cs': 'Kroky, galerie provozu, certifikáty. Partner vidí, jak děláte — nejen slogan.',
        'specs': 'Proces: 4 kroky\nGalerie: ano\nCertifikáty: ano',
        'specs_en': 'Process: 4 steps\nGallery: yes\nCertificates: yes',
        'specs_cs': 'Proces: 4 kroky\nGalerie: ano\nCertifikáty: ano',
        'image': 'examples/production.webp',
    },
    {
        'category': 2, 'name': 'Stavební firma', 'name_en': 'Construction company',
        'name_cs': 'Stavební firma',
        'price_from': None,
        'excerpt': 'Služby, zakázky, poptávka konzultace. V telefonu nemusíte zoomovat.',
        'excerpt_en': 'Services, projects, a consultation enquiry. No pinch-to-zoom on mobile.',
        'excerpt_cs': 'Služby, zakázky, poptávka konzultace. V telefonu nemusíte zoomovat.',
        'specs': 'Stránky: služby + zakázky\nPoptávka: ano\nMobil: ano',
        'specs_en': 'Pages: services + projects\nRequest: yes\nMobile: yes',
        'specs_cs': 'Stránky: služby + zakázky\nPoptávka: ano\nMobil: ano',
        'image': 'examples/construction.webp',
    },
    {
        'category': 3, 'name': 'Web kliniky', 'name_en': 'Clinic site',
        'name_cs': 'Web kliniky',
        'price_from': None,
        'excerpt': 'Služby, objednávka, kontakty. Poptávka přijde vám, neztratí se v messengeru.',
        'excerpt_en': 'Services, booking, contacts. The enquiry comes to you — not lost in a messenger.',
        'excerpt_cs': 'Služby, objednávka, kontakty. Poptávka přijde vám, neztratí se v messengeru.',
        'specs': 'Objednávka: formulář\nSlužby: katalog\nTelefon v hlavičce: ano',
        'specs_en': 'Booking: form\nServices: catalog\nPhone in the header: yes',
        'specs_cs': 'Objednávka: formulář\nSlužby: katalog\nTelefon v hlavičce: ano',
        'image': 'examples/clinic.webp',
    },
    {
        'category': 3, 'name': 'Web školy', 'name_en': 'School site',
        'name_cs': 'Web školy',
        'price_from': None,
        'excerpt': 'Programy, zápis na hodiny, pobočky. Rodiče pochopí z první obrazovky.',
        'excerpt_en': 'Programmes, class booking, branches. Parents understand from the first screen.',
        'excerpt_cs': 'Programy, zápis na hodiny, pobočky. Rodiče pochopí z první obrazovky.',
        'specs': 'Stránky: programy + kontakty\nZápis: ano\nJazyky: dle potřeby',
        'specs_en': 'Pages: programmes + contacts\nBooking: yes\nLanguages: as needed',
        'specs_cs': 'Stránky: programy + kontakty\nZápis: ano\nJazyky: dle potřeby',
        'image': 'examples/school.webp',
    },
]
