# Generated by Django 4.2.21 on 2026-02-23 09:24
# SQLite-safe: plain AddField (was Postgres-only ADD COLUMN IF NOT EXISTS).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='contract_file',
            field=models.FileField(blank=True, help_text='Персональний договір для цього посилання', null=True, upload_to='contracts/'),
        ),
    ]
